version: "2"
services:
  server:
    image: ktr0731/mirage-server
    env_file: .server.env
    environment:
      - TZ=Asia/Tokyo
    ports:
      - "8080:8080"

  web:
    image: ktr0731/mirage-web
    volumes:
      - ".htpasswd:/etc/nginx/.htpasswd"
    ports:
      - "80:80"
    links:
      - server
